In [2]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, StandardScaler, RobustScaler
from sklearn.linear_model import LinearRegression, SGDClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import f_regression, SelectKBest, VarianceThreshold, SelectKBest
import statsmodels.api as sm
from pandas import to_datetime
from pycaret.regression import *


In [69]:
test = pd.read_csv('../EDA_and_preprocessing/test.csv')

In [70]:
test['arr_delay'] = df['arr_delay']

In [71]:
test = test.dropna()

In [72]:
test = test.reset_index(drop=True)

In [151]:
carrier_dums = pd.get_dummies(df['op_unique_carrier'], drop_first=True)
depdum = pd.get_dummies(df['dep_hour'], drop_first=True)
arrdum = pd.get_dummies(df['arr_hour'], drop_first=True)
weekdum = pd.get_dummies(df['weekday'], drop_first=True)
distance_dums = pd.get_dummies(df['dist_cats'], drop_first=True)

In [153]:
weekdum.columns = ['tue', 'wed', 'thur', 'fri', 'sat', 'sun']

In [164]:
Rscaler = RobustScaler()
robust_scaled = Rscaler.fit_transform(X)
# Sscaler = StandardScaler()
# standard_scaled = pd.DataFrame(Sscaler.fit_transform(polyt))

C:\Users\broug\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['float', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\broug\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['float', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [165]:
robust_scaled.columns = X.columns


AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [773]:
X_train, X_test, y_train, y_test = train_test_split(df2, y, test_size=0.2, random_state=0)

In [458]:
f_regression(X_train, y_train)[1]

array([2.34892628e-081, 9.38861944e-060, 5.76631731e-093, 3.04702407e-065,
       8.76825224e-046, 5.97955621e-019, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.48348552e-002, 2.77405841e-028,
       0.00000000e+000, 4.88979293e-128, 1.31446939e-035, 8.38672876e-004,
       1.19270348e-019])

In [194]:
reg = LinearRegression()

In [452]:
reg.fit(X_train, y_train)    

LinearRegression()

In [453]:
reg.score(X_test, y_test)

0.4299953926383264

In [10]:
y = df2['arr_delay']

In [456]:
reg.coef_

array([-0.21148488,  0.02382765, -0.0597098 , -0.14823941, -0.11505665,
        0.26469984,  0.69218393,  0.81376967,  0.59369118,  0.04840041,
       -0.42302682, -0.54559768,  0.9105955 , -0.56719821, -0.0195271 ,
        0.10442781, -0.08490071])

In [630]:
_csv('../EDA_and_preprocessing/final_process.csv', index=False)

In [30]:
df2.drop(columns=['dep_hour_sin', 'dep_hour_cos', 'arr_hour_sin', 'arr_hour_cos', 'weekday_sin', 'weekday_cos'], inplace=True)

In [27]:
test = sm.add_constant(df2)
mod = sm.OLS(y, test.drop(columns=['arr_delay','dep_hour_sin', 'dep_hour_cos', 'arr_hour_sin', 'arr_hour_cos', 'weekday_sin', 'weekday_cos']))
print(mod.fit().summary())

                            OLS Regression Results                            
Dep. Variable:              arr_delay   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.435
Method:                 Least Squares   F-statistic:                     5559.
Date:                Tue, 12 Apr 2022   Prob (F-statistic):               0.00
Time:                        23:46:10   Log-Likelihood:            -4.9510e+05
No. Observations:              108140   AIC:                         9.902e+05
Df Residuals:                  108124   BIC:                         9.904e+05
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    7.6112 

In [155]:
test = pd.concat([X, distance_dums, carrier_dums],axis=1)

In [62]:
poly = PolynomialFeatures(degree=2)
polyt = poly.fit_transform(X)

In [623]:
ploycols = poly.get_feature_names_out(X.columns)
pd.DataFrame(polyt, columns=ploycols)

1  tail_taxi_total  taxi_total  airport_taxi_out_avg  \
0       1.0        21.869565        16.0             18.816138   
1       1.0        21.869565        22.0             18.816138   
2       1.0        21.869565        23.0             18.816138   
3       1.0        21.869565        16.0             18.816138   
4       1.0        21.869565        19.0             18.816138   
...     ...              ...         ...                   ...   
108135  1.0        12.812500        10.0              8.416667   
108136  1.0        12.812500        10.0              8.416667   
108137  1.0        12.812500        15.0              8.416667   
108138  1.0        12.812500        10.0              8.416667   
108139  1.0        24.000000        24.0             12.214286   

        airport_taxi_in_avg  tail_dep_delay  tail_arr_delay  crs_elapsed_time  \
0                  5.884615       -0.086957       -9.304348              81.0   
1                  5.884615       -0.086957       -9.304348              82.0   
2                  5.884615       -0.086957       -9.304348              81.0   
3                  5.884615       -0.086957       -9.304348              88.0   
4                  8.425434       -0.086957       -9.304348             260.0   
...                     ...             ...             ...               ...   
108135             4.375000      -10.625000       -8.750000              50.0   
108136             4.375000      -10.625000       -8.750000              50.0   
108137             4.375000      -10.625000       -8.750000              50.0   
108138             4.375000      -10.625000       -8.750000              50.0   
108139             4.400000      -10.000000       -3.000000              41.0   

        tail_speed  hourly_arr_delay  ...  tail_speed^2  \
0         6.140610         -4.100000  ...     37.707095   
1         6.140610         -6.444444  ...     37.707095   
2         6.140610          0.777778  ...     37.707095   
3         6.140610         -8.000000  ...     37.707095   
4         6.140610         -8.520833  ...     37.707095   
...            ...               ...  ...           ...   
108135    2.370632         -8.500000  ...      5.619895   
108136    2.370632        -25.000000  ...      5.619895   
108137    2.370632        -25.000000  ...      5.619895   
108138    2.370632          0.000000  ...      5.619895   
108139    2.687500         -3.000000  ...      7.222656   

        tail_speed hourly_arr_delay  tail_speed hourly_dep_delay  \
0                        -25.176502                   102.855223   
1                        -39.572822                    92.345332   
2                          4.776030                    -2.686517   
3                        -49.124883                    45.884005   
4                        -52.323117                     0.731025   
...                             ...                          ...   
108135                   -20.150370                   -17.779738   
108136                   -59.265794                   -59.265794   
108137                   -59.265794                   -71.118953   
108138                     0.000000                    11.853159   
108139                    -8.062500                   -26.875000   

        tail_speed speed  hourly_arr_delay^2  \
0              29.146277           16.810000   
1              26.875139           41.530864   
2              25.867321            0.604938   
3              27.964671           64.000000   
4              51.093027           72.604601   
...                  ...                 ...   
108135          6.116230           72.250000   
108136          6.116230          625.000000   
108137          5.560209          625.000000   
108138          6.795811            0.000000   
108139          7.222656            9.000000   

        hourly_arr_delay hourly_dep_delay  hourly_arr_delay speed  \
0                              -68.675000              -19.460563   
1  

In [3]:
df = pd.read_csv('../EDA_and_preprocessing/final_process.csv')

In [31]:
reg1 = setup(data = df2, target = 'arr_delay', feature_interaction = True, feature_ratio = True)

In [32]:
best = compare_models()

In [33]:
print(best)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=5221, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)


In [34]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [167]:
from F_eng import process_taxi_times_median, process_carrier_id, tail_num_median, airport_hour_medians
df = process_taxi_times_median(df)
df = process_carrier_id(df)
df = tail_num_median(df)
df = airport_hour_medians(df)

In [168]:
df = df.dropna()

In [169]:
df = df.reset_index(drop=True)

In [146]:
y = df['arr_delay']

In [147]:
X = df[['crs_elapsed_time', 'dep_hour', 'arr_hour', 'month_day', 'weekday', 'hourly_arr_delay', 'hourly_dep_delay', 'tail_arr_delay', 'tail_dep_delay', 'airport_taxi_in_avg', 'airport_taxi_out_avg', 'tail_taxi_total', 'median_airport_taxi_in', 'std_airport_taxi_in', 'median_airport_taxi_out', 'std_airport_taxi_out', 'per_airport_taxi_total', 'median_tail_taxi_total', 'carrier_dep_mean', 'carrier_arr_mean', 'carrier_dep_median', 'carrier_dep_std',
 'carrier_arr_median',
 'carrier_arr_std',
 'median_tail_dep_delay',
 'median_tail_arr_delay',
 'std_tail_dep_delay',
 'std_tail_arr_delay',
 'weekly_median_arr_delay',
 'weekly_std_arr_delay',
 'weekly_mean_arr_delay',
 'weekly_median_dep_delay',
 'weekly_std_dep_delay',
 'weekly_mean_dep_delay',
 'hourly_median_arr_delay',
 'hourly_std_arr_delay',
 'hourly_median_dep_delay',
 'hourly_std_dep_delay']]

In [112]:
X = df[['tail_taxi_total', 'taxi_total', 'airport_taxi_out_avg', 'airport_taxi_in_avg', 'tail_dep_delay', 'tail_arr_delay', 'crs_elapsed_time', 'hourly_arr_delay', 'hourly_dep_delay', 'dep_hour', 'arr_hour']]

In [172]:
df.columns

Index(['fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier',
       'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time', 'dep_time',
       'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled', 'diverted',
       'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance',
       'dist_cats', 'dep_hour', 'arr_hour', 'month_day', 'weekday',
       'hourly_arr_delay', 'hourly_dep_delay', 'tail_arr_delay',
       'tail_dep_delay', 'airport_taxi_in_avg', 'airport_taxi_out_avg',
       'taxi_total', 'tail_taxi_total', 'median_airport_taxi_in',
       'std_airport_taxi_in', 'median_airport_taxi_out',
       'std_airport_taxi_out', 'per_airport_taxi_total',
       'median_tail_taxi_total', 'carrier_dep_mean', 'carrier_arr_mean',
       'carrier_dep_median'

In [161]:
X = pd.concat([depdummies, arrdummies, X, weekdum, carrier_dums, distance_dums], axis=1)

In [6]:
df2 = pd.read_csv('rscore0.435.csv')
df2

tail_taxi_total  taxi_total  airport_taxi_out_avg  \
0             21.869565        16.0             18.816138   
1             21.869565        22.0             18.816138   
2             21.869565        23.0             18.816138   
3             21.869565        16.0             18.816138   
4             21.869565        19.0             18.816138   
...                 ...         ...                   ...   
108135        12.812500        10.0              8.416667   
108136        12.812500        10.0              8.416667   
108137        12.812500        15.0              8.416667   
108138        12.812500        10.0              8.416667   
108139        24.000000        24.0             12.214286   

        airport_taxi_in_avg  tail_dep_delay  tail_arr_delay  crs_elapsed_time  \
0                  5.884615       -0.086957       -9.304348              81.0   
1                  5.884615       -0.086957       -9.304348              82.0   
2                  5.884615       -0.086957       -9.304348              81.0   
3                  5.884615       -0.086957       -9.304348              88.0   
4                  8.425434       -0.086957       -9.304348             260.0   
...                     ...             ...             ...               ...   
108135             4.375000      -10.625000       -8.750000              50.0   
108136             4.375000      -10.625000       -8.750000              50.0   
108137             4.375000      -10.625000       -8.750000              50.0   
108138             4.375000      -10.625000       -8.750000              50.0   
108139             4.400000      -10.000000       -3.000000              41.0   

        tail_speed  hourly_arr_delay  hourly_dep_delay  dep_hour_sin  \
0         6.140610         -4.100000         16.750000     -0.965926   
1         6.140610         -6.444444         15.038462     -0.965926   
2         6.140610          0.777778         -0.437500      0.965926   
3         6.140610         -8.000000          7.472222     -0.866025   
4         6.140610         -8.520833          0.119048      0.500000   
...            ...               ...               ...           ...   
108135    2.370632         -8.500000         -7.500000      0.707107   
108136    2.370632        -25.000000        -25.000000     -0.500000   
108137    2.370632        -25.000000        -30.000000     -0.500000   
108138    2.370632          0.000000          5.000000      0.866025   
108139    2.687500         -3.000000        -10.000000     -0.965926   

        dep_hour_cos  arr_hour_sin  arr_hour_cos  weekday_sin  weekday_cos  \
0           0.258819     -0.866025  5.000000e-01     0.781831     0.623490   
1           0.258819     -0.866025  5.000000e-01     0.974928    -0.222521   
2          -0.258819      0.866025 -5.000000e-01     0.433884    -0.900969   
3          -0.500000     -0.965926 -2.588190e-01     0.781831     0.623490   
4          -0.866025     -0.965926 -2.588190e-01    -0.433884    -0.900969   
...              ...           ...           ...          ...          ...   
108135     -0.707107      0.500000 -8.660254e-01    -0.781831     0.623490   
108136      0.866025     -0.258819  9.659258e-01     0.433884    -0.900969   
108137      0.866025     -0.258819  9.659258e-01    -0.433884    -0.900969   
108138      0.500000      0.965926  2.588190e-01    -0.781831     0.623490   
108139     -0.258819     -1.000000 -1.836970e-16     0.433884    -0.900969   

           speed  
0       4.746479  
1       4.376623  
2       4.212500  
3       4.554054  
4       8.320513  
...          ...  
108135  2.580000  
108136  2.580000  
108137  2.345455  
108138  2.866667  
108139  2.687500  

[108140 rows x 17 columns]

In [157]:
vt = VarianceThreshold(0.1)
trans = vt.fit_transform(X)
trans = pd.DataFrame(trans, columns=X.columns[vt.get_support()])
trans

crs_elapsed_time  dep_hour  arr_hour  month_day  weekday  \
0                   81.0      19.0      20.0        1.0      1.0   
1                   80.0      19.0      21.0       30.0      1.0   
2                   70.0      19.0      20.0       29.0      1.0   
3                   70.0      19.0      20.0       15.0      1.0   
4                   70.0      19.0      20.0       22.0      1.0   
...                  ...       ...       ...        ...      ...   
108127              35.0      13.0      14.0       30.0      1.0   
108128             225.0      18.0      22.0       17.0      2.0   
108129              50.0       4.0       5.0       28.0      6.0   
108130              35.0      15.0      15.0        7.0      6.0   
108131              35.0      15.0      15.0       28.0      6.0   

        hourly_arr_delay  hourly_dep_delay  tail_arr_delay  tail_dep_delay  \
0              -4.100000             16.75       -9.304348       -0.086957   
1             -10.181818             16.75       -4.344828        3.517241   
2              10.300000             16.75        0.083333        7.791667   
3              10.300000             16.75        2.944444        6.805556   
4              10.300000             16.75       14.166667       37.000000   
...                  ...               ...             ...             ...   
108127        -25.000000            -30.00       -8.750000      -10.625000   
108128        -51.000000            -10.00        9.600000       13.800000   
108129          0.000000              5.00       -8.750000      -10.625000   
108130         -5.000000             -5.00        0.666667       -2.750000   
108131         -5.000000             -5.00       -8.750000      -10.625000   

        airport_taxi_in_avg  ...  weekly_mean_arr_delay  \
0                  5.884615  ...              -3.394737   
1                  5.884615  ...              -3.394737   
2                  6.662893  ...               5.153203   
3                  6.662893  ...               5.153203   
4                  6.662893  ...               5.153203   
...                     ...  ...                    ...   
108127             4.400000  ...             -16.500000   
108128             6.430380  ...               4.400000   
108129             4.375000  ...              -5.400000   
108130             4.375000  ...              -5.400000   
108131             4.375000  ...              -5.400000   

        weekly_median_dep_delay  weekly_std_dep_delay  weekly_mean_dep_delay  \
0                          -3.0             24.375420               4.303502   
1                          -3.0             24.375420               4.303502   
2                          -3.0             24.375420               4.303502   
3                          -3.0             24.375420               4.303502   
4                          -3.0             24.375420               4.303502   
...                         ...                   ...                    ...   
108127                    -30.0             23.513098             -30.000000   
108128                     -6.0              5.656854              -6.000000   
108129                      0.0             10.408330              -3.333333   
108130                     -5.0              7.071068              -5.000000   
108131                     -5.0              7.071068              -5.000000   

        hourly_departures  hourly_arrivals  hourly_median_arr_delay  \
0                   154.0             57.0                     -6.0   
1                   154.0             61.0                    -12.0   
2                   154.0            162.0                     -8.0   
3                   154.0            162.0                     -8.0   
4                   154.0            162.0                     -8.0   
...                   ...              ...                      ...   
108127                2.0              2.0                    -25.0   
108128          

In [158]:
df_corr = X.corr().abs()

indices = np.where(df_corr > 0.8) 
indices = [(df_corr.index[x], df_corr.columns[y]) 
for x, y in zip(*indices)
    if x != y and x < y]

for idx in indices:
    try:
        X.drop(idx[1], axis = 1, inplace=True)
    except KeyError:
        pass

C:\Users\broug\AppData\Local\Temp\ipykernel_7176\3057310379.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(idx[1], axis = 1, inplace=True)
C:\Users\broug\AppData\Local\Temp\ipykernel_7176\3057310379.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(idx[1], axis = 1, inplace=True)
C:\Users\broug\AppData\Local\Temp\ipykernel_7176\3057310379.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(idx[1], axis = 

In [49]:
skb = SelectKBest(f_regression, k=10)
X = skb.fit_transform(test, y)
test.columns[skb.get_support()]
X = pd.DataFrame(X,columns=test.columns[skb.get_support()])

In [730]:
minv = y.min()
maxv = y.max()
bins = np.linspace(minv, maxv, 6)
bins

array([-85. , -28.2,  28.6,  85.4, 142.2, 199. ])

In [736]:
labels = ['early', 'on_time', '15_mins_late', '60mins_late', '60+']

In [81]:
y = df['arr_delay']
X= df.drop(columns='arr_delay')

In [769]:
y = pd.qcut(y, 4)

In [737]:
pd.cut(y, bins=bins, labels=labels, include_lowest=True)

0           early
1           early
2             60+
3           early
4           early
           ...   
108135      early
108136      early
108137      early
108138    on_time
108139    on_time
Name: arr_delay, Length: 108140, dtype: category
Categories (5, object): ['early' < 'on_time' < '15_mins_late' < '60mins_late' < '60+']

In [772]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
logr = LogisticRegression()
le = LabelEncoder()
yt = le.fit_transform(y)

In [762]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)
pipe.score(X_train, y_train)

0.36904706861475867

In [759]:
y_pred = pipe.predict(X_test)

In [760]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[2394  813  219   30  218  214]
 [1283 1184  553  121  377  281]
 [ 847  975  669  171  601  349]
 [ 575  597  566  226  848  386]
 [ 455  442  377  174 1307  786]
 [ 307  260  151   46  638 2188]]


In [767]:
from sklearn.naive_bayes import GaussianNB
bay = GaussianNB()
bay.fit(X_train, y_train)
bay.score(X_train, y_train)
y_pred = bay.predict(X_test)
confusion_matrix(y_pred, y_test)

0.3327862030700943

In [778]:
SGD = make_pipeline(StandardScaler(), SGDClassifier())
SGD.fit(X_train, y_train)
y_pred = SGD.predict(X_test)
SGD.score(X_train, y_train)

0.4523534307379323

In [ ]:
import pandas as pd 
import numpy as np

In [27]:
test['arr_delay'] = df['arr_delay']

In [28]:
test = test.dropna()

In [32]:
test = test.drop(columns='arr_delay')